apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: roognis

resources:
  - namespace.yaml
  - postgres/pvc.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - auth/deployment.yaml
  - auth/service.yaml
  - auth/hpa.yaml
  - ai/deployment.yaml
  - ai/service.yaml
  - rag/deployment.yaml
  - rag/service.yaml
  - quiz/deployment.yaml
  - quiz/service.yaml
  - practice/deployment.yaml
  - practice/service.yaml
  - discover/deployment.yaml
  - discover/service.yaml
  - analytics/deployment.yaml
  - analytics/service.yaml
  - lms/deployment.yaml
  - lms/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress/ingress.yaml
